server:
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.jks
    key-store-password: changeit
    key-alias: server-alias
    protocol: TLS
    enabled-protocols: TLSv1.2
  port: 8443
  session:
    timeout: 3600

logging.level.org.springframework.security: TRACE


spring.security.oauth2.client:
    registration:
      google:
        client-id: ${GOOGLE_CLIENT_ID:client-id}
        client-secret: ${GOOGLE_CLIENT_SECRET:client-secret}
      instagram:
        provider: instagram
        client-name: instagram
        client-id: ${INST_CLIENT_ID:client-id}
        client-secret: ${INST_CLIENT_SECRET:client-secret}
        redirect-uri: https://localhost:8443/login/oauth2/code/instagram
        authorization-grant-type: authorization_code
        client-authentication-method: client_secret_post
        scope: user_profile,user_media
    provider:
      instagram:
        authorization-uri: https://api.instagram.com/oauth/authorize
        token-uri: https://api.instagram.com/oauth/access_token
        user-info-uri: https://graph.instagram.com
        user-info-authentication-method: post
        user-name-attribute: id
#
#
#spring.security.oauth2.client.registration.linkedin.provider=linkedin
#spring.security.oauth2.client.registration.linkedin.client-name=Linkedin
#spring.security.oauth2.client.registration.linkedin.client-id=******
#spring.security.oauth2.client.registration.linkedin.client-secret=******
#spring.security.oauth2.client.registration.linkedin.redirect-uri=*****
#spring.security.oauth2.client.registration.linkedin.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.linkedin.client-authentication-method=form
#spring.security.oauth2.client.registration.linkedin.scope=r_emailaddress,r_liteprofile
#spring.security.oauth2.client.provider.linkedin.authorization-uri=https://www.linkedin.com/oauth/v2/authorization
#spring.security.oauth2.client.provider.linkedin.token-uri=https://www.linkedin.com/oauth/v2/accessToken
#spring.security.oauth2.client.provider.linkedin.user-info-uri=https://api.linkedin.com/v2/me
#spring.security.oauth2.client.provider.linkedin.user-info-authentication-method=post
